{{- if .Values.zebra.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zebra.name }}
  labels:
    app: {{ .Values.zebra.name }}
    app.kubernetes.io/name: zebra
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: validator
spec:
  type: {{ .Values.zebra.service.type }}
  selector:
    app: {{ .Values.zebra.name }}
  ports:
    - port: {{ if .Values.zebra.testnet }}18232{{ else }}8232{{ end }}
      targetPort: {{ if .Values.zebra.testnet }}18232{{ else }}8232{{ end }}
      protocol: TCP
      name: rpc
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
{{- end }}